name: relon-backend
services:
  relon-api:
    env_file:
      - .env
      - .env.relonapi
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - PORT=80
      - MONGO_URI=mongodb://${RELON_BACKEND_USER}:${RELON_BACKEND_PASSWORD}@relon-backend-db/${RELON_BACKEND_DB}
      # When running inside Docker on some platforms (Windows/macOS/WSL),
      # file system events can be unreliable. Enabling polling helps nodemon detect changes.
      # - CHOKIDAR_USEPOLLING=1
    ports:
      - "${HOST_RELON_API_PORT}:80"
    # volumes:
    #   # bind-mount the source directory so changes on the host are visible in the container
    #   - ./src:/app/src
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
    networks:
      - relon-backend-net
    depends_on:
      - relon-backend-db
  
  relon-backend-db:
    image: mongo:6.0
    env_file:
      - .env.db
      - .env
    ports:
      - "${HOST_DB_PORT}:${CONTAINER_DB_PORT}"
    volumes:
      - type: bind
        source: mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true

      - type: volume
        source: relon-backend-data
        target: /data/db
    networks:
      - relon-backend-net

volumes:
  relon-backend-data:

networks:
  relon-backend-net: