name: assessment-backend
services:
  api-service:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      - PORT=8000
      - MONGO_URI=mongodb://${ASSESSMENT_BACKEND_USER}:${ASSESSMENT_BACKEND_PASSWORD}@mongo-db/${ASSESSMENT_BACKEND_DB}
    ports:
      - "${HOST_ASSESSMENT_API_PORT}:8000"
    networks:
      - assessment-backend-net
    depends_on:
      mongo-db:
        condition: service_healthy
      redis_db:
        condition: service_healthy
  
  mongo-db:
    image: mongo:6.0
    env_file:
      - .env.db
      - .env
    ports:
      - "${HOST_DB_PORT}:${CONTAINER_DB_PORT}"
    volumes:
      - type: bind
        source: mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: assessment-db-data
        target: /data/db
    networks:
      - assessment-backend-net
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
  
  redis_db:
    image: redis:7.2-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - assessment-backend-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  assessment-db-data:
  redis_data:

networks:
  assessment-backend-net: